### ISSUE TITLE
Request: Support MacOS 13 Ventura

### ISSUE THREAD

**Issue by Aradesh3k** [kevinhermawan/Canvas#14]
I'm looking for something to replace OpenAI's labs website, and this looks like it might be what I'm looking for. I'm bummed to see that it requires Sonoma. I'm using an iMac that only supports 13.6.7 Ventura as the latest update. Any chance you could release a version that supports that? 
thanks!

**Comment by kevinhermawan** [comment]
Hi @Aradesh3k, I’m sorry, but I use an API that requires macOS Sonoma, so I'm unable to add support for macOS 13.
