### ISSUE TITLE
Please notarize your releases

### ISSUE THREAD

**Issue by chrismessina** [kevinhermawan/Canvas#3]
Hello. Upon attempting to install the current release, I had to hop through two hoops:

![Hoop 1](https://github.com/kevinhermawan/Canvas/assets/22610/5701c206-0f19-4e2d-a168-7e8d0eff0508)
![Hoop 2](https://github.com/kevinhermawan/Canvas/assets/22610/dece585d-aa6d-4746-aa7a-2df54357b92e)

It'd be great if you could [notarize your releases](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution) so this could be avoided. Thanks!

**Comment by kevinhermawan** [comment]
Ah, looks like I missed the step. I just updated the asset. Thanks, @chrismessina! 🙏🏼
