### ISSUE TITLE
Image generation history or auto-save

### ISSUE THREAD

**Issue by DamienSchreurs** [kevinhermawan/Canvas#5]
Without realising it, I lost the first image that I generated because I didn't know that leaving the "Image Generation" section would refresh that page.
For the second image, I managed to save it via a right-click.
Could it be possible to save the image generation history, or enable image auto-save inside a default or user-defined folder?
Keep up the good work!
Cheers,
Damien

**Comment by kevinhermawan** [comment]
Hi @DamienSchreurs, I appreciate your feedback and suggestions. Sorry to hear that you lost your first generated image. Unfortunately, generation history isn't possible at the moment due to the API result returning a URL with expiration. However, I'll see what I can do about adding an auto-save feature.

**Comment by DamienSchreurs** [comment]
Thanks a lot for the reply and the explanations, @kevinhermawan!
The auto-save feature would already be a great thing, if you can figure out a way to do that.
Cheers!

**Comment by kevinhermawan** [comment]
Hi @DamienSchreurs, I just wanted to let you know that the auto-save feature was added in [version 1.0.3](https://github.com/kevinhermawan/Canvas/releases/tag/v1.0.3). Please let me know if it's working as expected!

**Comment by DamienSchreurs** [comment]
Hi Kevin, I've been able to test version 1.0.3 and it indeed works as
expected.

Many thanks for implementing this so quickly!

Cheers,
Damien
ᐧ
ᐧ
ᐧ

**Comment by kevinhermawan** [comment]
Thank you for confirming, @DamienSchreurs!
